http:
  host: "0.0.0.0:20125"

kafka:
  host: "172.17.101.188:9092"
  topic: "runnergo"
  key: "kafka:report:partition"
  runKafkaPartition: "RunKafkaPartition"

reportRedis:
  address: "172.17.101.191:6398"
  password: "apipost"
  db: 15

redis:
  address: "172.17.101.191:6398"
  password: "apipost"
  db: 15

log:
  path: "/data/logs/RunnerGo/RunnerGo-collector-info.log"

management:
  notifyStopStress: "https://manager.runnergo.cc/management/api/v1/plan/notify_stop_stress"